### ISSUE TITLE
panda_arm_controller becomes inactive

### ISSUE THREAD

**Issue by RaMathuZen** [moveit/mujoco_ros2_control_examples#5]
when launching `peg_in_hole` example, `admittance_controller` doesn't get configured and because of which `panda_arm_controller` becomes inactive.

Admittance Controller:
>  [mujoco_ros2_control-5] [ERROR] [1727793650.493108493] [AdmittanceRule]: Exception while loading the IK plugin 'kinematics_interface_kdl/KinematicsInterfaceKDL': 'According to the loaded plugin descriptions the class kinematics_interface_kdl/KinematicsInterfaceKDL with base class type kinematics_interface::KinematicsInterface does not exist. Declared types are '
[mujoco_ros2_control-5] [WARN] [1727793650.497118914] [admittance_controller]: Error occurred while doing error handling.
[mujoco_ros2_control-5] [ERROR] [1727793650.497461910] [controller_manager]: After configuring, controller 'admittance_controller' is in state 'unconfigured' , expected inactive.
[spawner-7] [ERROR] [1727793650.505394606] [spawner_admittance_controller]: Failed to configure controller
[rviz2-1] [ERROR] [1727793650.915755559] [moveit_ros_visualization.motion_planning_frame]: Action server: /recognize_objects not available
[INFO] [spawner-8]: process has finished cleanly [pid 60530]
[ERROR] [spawner-7]: process has died [pid 60528, exit code 1, cmd '/opt/ros/humble/lib/controller_manager/spawner admittance_controller -c /controller_manager --ros-args'].

panda_arm_controller:

> [mujoco_ros2_control-5] [WARN] [1727793664.916408405] [controller_manager]: The following controller with name 'admittance_controller' is not active and will not be activated.
[mujoco_ros2_control-5] [WARN] [1727793664.916604135] [controller_manager]: Could not activate controller with name 'panda_arm_controller'. Check above warnings for more details. Check the state of the controllers and their required interfaces using `ros2 control list_controllers -v` CLI to get more information.
[mujoco_ros2_control-5] [ERROR] [1727793664.916635540] [controller_manager]: Aborting, no controller is switched! (::STRICT switch)
[spawner-9] [ERROR] [1727793664.935683283] [spawner_panda_arm_controller]: Failed to activate controller
[rviz2-1] [INFO] [1727793665.144071355] [interactive_marker_display_94080952656192]: Service response received for initialization
[ERROR] [spawner-9]: process has died [pid 60559, exit code 1, cmd '/opt/ros/humble/lib/controller_manager/spawner panda_arm_controller -c /controller_manager --ros-args']

mujoco: 3.1.5

**Comment by sangteak601** [comment]
Hi @RaMathuZen,
Thanks for reporting the issue. It seems you didn't install the dependency `kinematics_interface_kdl`.

Can you try installing dependencies before launching them?
```
rosdep update && rosdep install --from-paths ./ --ignore-src -y
```

**Comment by RaMathuZen** [comment]
@sangteak601 Yeah It works now. Thanks.
